services:
  db:
    container_name: blog_db
    image: postgres:15.2
    restart: always
    ports:
      - '5000:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
